### ISSUE TITLE
clear image list

### ISSUE THREAD

**Issue by sifatm360ict** [shubham-gupta-16/multi_image_picker_view#10]
can I clear image list?

**Comment by shubham-gupta-16** [comment]
> can I clear image list?

Sorry, I can't get it. Do you mean to add a button somewhere to clear all images?

Provide more details. I will be happy to implement it.

**Comment by sifatm360ict** [comment]
Something like that we can clear the image list after upload data to server
or anywhere after use.

**Comment by shubham-gupta-16** [comment]
@sifatm360ict 
You can run for-each loop on the images list and call `controller.removeImage(imageFile);` to clear all the images.

**Comment by sifatm360ict** [comment]
I think this is not user friendly.can i try to contribute in your project?

**Comment by shubham-gupta-16** [comment]
@sifatm360ict Sure.

**Comment by shubham-gupta-16** [comment]
Method added in controller `clearImages()` to clear all selected images.

**Comment by shubham-gupta-16** [comment]
@sifatm360ict You can find it in version `0.0.10`.
