### ISSUE TITLE
Add property so images can be saved with data

### ISSUE THREAD

**Issue by justin-blue** [shubham-gupta-16/multi_image_picker_view#17]
Please add a boolean flag to the MultiImagePickerView so that pickImages() can use the `withData` property. Without this it is not possible to upload images to FireStore as the default for this property is false.
 `/// manually pick images. i.e. on click on external button.
  /// this method open Image picking window.
  /// It returns [Future] of [bool], true if user has selected images.
  Future<bool> pickImages() async {
    FilePickerResult? result = await FilePicker.platform.pickFiles(
        withData: true,
        allowMultiple: this.maxImages > 1 ? true : false,
        type: FileType.custom,
        allowedExtensions: allowedImageTypes);`

**Comment by shubham-gupta-16** [comment]
@justin-blue Version 0.0.14 is released. Now you can set `withData` or `withReadStream` in MultiImagePickerController.
