### ISSUE TITLE
Duplicated key null found in children fail when upload photo

### ISSUE THREAD

**Issue by ernarim** [shubham-gupta-16/multi_image_picker_view#2]
The following assertion was thrown building MultiImagePickerView(state: _MultiImagePickerViewState#048c0):
Duplicated key null found in children
'package:flutter_reorderable_grid_view/widgets/reorderable_builder.dart':
Failed assertion: line 162 pos 16: 'false'

**Comment by tanmoy27112000** [comment]
Same for me @shubham-gupta-16

**Comment by shubham-gupta-16** [comment]
Issue resolved in `Release 0.0.4`

**Comment by sifatm360ict** [comment]
Duplicated key null found in children still i am getting this issue. Is there any solution?
