### ISSUE TITLE
FilePicker usage should change

### ISSUE THREAD

**Issue by anton-definit** [shubham-gupta-16/multi_image_picker_view#20]
In `/lib/src/multi_image_picker_controller.dart` `line 41` you are using `FileType.custom`. Is there any specific reason for that?
In my case, on iOS, it seems to be causing the file picker to open iCloud instead of the image app.
I guess that you will be able to fix by changing the `FileType` from `custom` to `image` or `media`.  Of couse the you would be forced to get rid of the custom extension filters.

**Comment by shubham-gupta-16** [comment]
@anton-definit I don't have access to iOS. Thank you for finding this issue. I will fix it very soon. 

The current version uses `file_picker` for all the platforms, I think I should use `image_picker` for iOS platform and `file_picker` for other platforms.

**Comment by shubham-gupta-16** [comment]
@anton-definit are you sure `FileType.image` or `FileType.media` works? Can you please check it by changing the params in file `multi_image_picker_controller.dart` on `line 41`?

**Comment by anton-definit** [comment]
I forked your plugin, changed `line 41` to `FileType.image` and commented out `allowedExtensions: allowedImageTypes` at `line 44` because when using `FileType.image` we are not allowed to set allowed extension. This works on Andorid. I will test it on iOS later today :-)

**Comment by shubham-gupta-16** [comment]
`allowedImageTypes` is one of the best featue of this package. Even `image_picker` package doesn't provide it. Is this can be possible to solve the issue without removing the `allowedImageTypes` feature?

**Comment by anton-definit** [comment]
I don't agree. The best feature in your plugin is max images limit :-) at least in my case.
But of course it would be sad to remove the `allowedExtensions` feature from the picker. I guess we have to file a feature request to FilePicker and tell them we want them to enable `allowedExtensions` when `FileType.image` is selected. But my guess is that it would not be so straight forward for them.

**Comment by shubham-gupta-16** [comment]
Ok then, test it in iOS let me know. Also maybe issue #4 can also be solved by this. I will remove the `allowedImageTypes` feature to solve the issue. I will try to make it more flexible, i.e., `allowedImageTypes` is only supported on Android, Web, and Windows. Let me know your opinion.

I was also working on v1 of this package. You can find it on branch v1. I will be happy to get some feedback from you.

**Comment by anton-definit** [comment]
I am testing on iOS tonight or tomorrow. Then I will get back to you.
I see that you are processing the picked image files after the picker is closed and running a `where` condition to filter out images with extensions that are not allowed:
```
 _addImages(result.files
          .where((e) =>
              e.extension != null &&
              allowedImageTypes.contains(e.extension?.toLowerCase()))
          .map((e) => ImageFile(UniqueKey().toString(),
              name: e.name,
              extension: e.extension!,
              bytes: e.bytes,
              readStream: e.readStream,
              path: !kIsWeb ? e.path : null)));
```
This might still be a nice feature? And it works across all platforms.

In #4 you are suggested to use image_picker instead of file_picker. I wouldnt recommend that because image_picker wont let you stream the picked files and therefor you will not be able to set a max images limit. Which of course is the most valuable feature ;-)

**Comment by anton-definit** [comment]
Just tested on iOS. It works

**Comment by shubham-gupta-16** [comment]
@anton-definit Sorry for the late reply. I got access to a MacBook. I will fix this issue in this week.

**Comment by gidrokolbaska** [comment]
> @anton-definit Sorry for the late reply. I got access to a MacBook. I will fix this issue in this week.

Any updates?

**Comment by gidrokolbaska** [comment]
Oh and by the way, by commenting out the allowedExtensions: allowedImageTypes like anton did, throws a platform exception if you select, let's say, an image with HEIF extension

**Comment by shubham-gupta-16** [comment]
> > @anton-definit Sorry for the late reply. I got access to a MacBook. I will fix this issue in this week.
> 
> Any updates?

Version `1.0.0` is released with **Major Changes** 🚀.

**The package no longer handles the image-picking logic**. You have to define your picker logic as you want. You can either choose `image_picker` or `file_picker` or any plugin you want with your own image/file picking logic. This will give you more flexibility and control.

Check the README.md for docs and migrating guidelines.
