### ISSUE TITLE
Avoid adding same image multiple times

### ISSUE THREAD

**Issue by philitell** [shubham-gupta-16/multi_image_picker_view#25]
I would be nice to be able to add only images that havn't been added yet. At the moment it is possible to add the same image multiple times (identical name and image path). 
![Screenshot_1686914866](https://github.com/shubham-gupta-16/multi_image_picker_view/assets/87064261/ccd484ee-9d97-4fde-84a6-f07672ba1a6d)

**Comment by shubham-gupta-16** [comment]
Version `1.0.0` is released with **Major Changes** 🚀.

**The package no longer handles the image-picking logic**. You have to define your picker logic as you want. You can either choose `image_picker` or `file_picker` or any plugin you want with your own image/file picking logic. This will give you more flexibility and control.

You have to handle this logic by comparing if the image already exists in the controller.
```dart
Future<List<ImageFile>> picker(bool allowMultiple) async {
    final list = await pickImagesUsingImagePicker(allowMultiple);
    return list.where((e) =>
        !controller.images.any((image) => e == image)).toList();
  }
```

Check the README.md for docs and migrating guidelines.
