### ISSUE TITLE
help

### ISSUE THREAD

**Issue by BlackTryyy** [shubham-gupta-16/multi_image_picker_view#28]
I was wondering how to set it to open from recents instead of photos when using our component in ios
![f86cd5e4614c7b2d7f1c6bd882472db](https://github.com/shubham-gupta-16/multi_image_picker_view/assets/131345116/5f506b8e-e8b2-4ca3-aff0-3971f8b189b3)

**Comment by shubham-gupta-16** [comment]
under development

**Comment by BlackTryyy** [comment]
> under development
I did this by changing the type: FileType.media, referring to the previous issues, but how do I embed a photo in the selection,Thanks

**Comment by shubham-gupta-16** [comment]
Version `1.0.0` is released with **Major Changes** 🚀.

**The package no longer handles the image-picking logic**. You have to define your picker logic as you want. You can either choose `image_picker` or `file_picker` or any plugin you want with your own image/file picking logic. This will give you more flexibility and control.

Check the **README.md** for docs and migrating guidelines.
