### ISSUE TITLE
[maxImages] only works with view,u should also apply for when user picking images with selectableImages=N 

### ISSUE THREAD

**Issue by At738343** [shubham-gupta-16/multi_image_picker_view#29]

**Comment by shubham-gupta-16** [comment]
Version `1.0.0` is released with major changes. 

The package no longer handles the image-picking logic. You have to define your picker logic as you want. You can either choose `image_picker` or `file_picker` or any plugin you want with your own image/file picking logic.  This will give you more flexibility and controls.

Check the `README.md` for docs and migrating guidelines.

**Comment by shubham-gupta-16** [comment]
```
final controller = MultiImagePickerController(
    picker: (bool allowMultiple) async {
      // use image_picker or file_picker to pick images `pickImages`
      final pickedImages = await pickImages(allowMultiple);
      // convert the picked image list to `ImageFile` list and return it.
      return pickedImages.map((e) => convertToImageFile(e)).toList();
    }
);
```

You have to write your own `pickImages` function in which you can handle selectableImages logic.
