### ISSUE TITLE
imageFile returns zero byte even though it is not equal null

### ISSUE THREAD

**Issue by MariamAhmed12-hub** [shubham-gupta-16/multi_image_picker_view#3]

**Comment by shubham-gupta-16** [comment]
@MariamAhmed12-hub For Mobile and Desktop platform, you will get path and for Web platform, you will get bytes.

**Comment by shubham-gupta-16** [comment]
I planned to implement more reliable solution before `v1.0.0`

**Comment by shubham-gupta-16** [comment]
@MariamAhmed12-hub Version 0.0.14 is released. Now you can set `withData` to true in MultiImagePickerController. By this, bytes will never be 0. See Readme for more info.
