### ISSUE TITLE
No option for image quality

### ISSUE THREAD

**Issue by moinkhan780** [shubham-gupta-16/multi_image_picker_view#7]

**Comment by shubham-gupta-16** [comment]
Version `1.0.0` is released with **Major Changes** 🚀.

**The package no longer handles the image-picking logic.** You have to define your picker logic as you want. You can either choose `image_picker` or `file_picker` or any plugin you want with your own image/file picking logic. This will give you more flexibility and control.

The logic for image quality can be implemented by yourself.

Check the README.md for docs and migrating guidelines.
