### ISSUE TITLE
Multiple widgets used the same GlobalKey. version 0.0.7

### ISSUE THREAD

**Issue by moinkhan780** [shubham-gupta-16/multi_image_picker_view#8]

**Comment by shubham-gupta-16** [comment]
Can you provide mode details or logs?

**Comment by sifatm360ict** [comment]
======== Exception caught by widgets library =======================================================
The following assertion was thrown while finalizing the widget tree:
Multiple widgets used the same GlobalKey.

The key [GlobalKey#bf651] was used by multiple widgets. The parents of those widgets were:
- Container-[GlobalKey#acc02]
- Transform(dependencies: [Directionality], renderObject: RenderTransform#523e7)
A GlobalKey can only be specified on one widget at a time in the widget tree.
When the exception was thrown, this was the stack: 
#0      BuildOwner._debugVerifyGlobalKeyReservation.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:flutter/src/widgets/framework.dart:2883:13)
#1      _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:617:13)
#2      BuildOwner._debugVerifyGlobalKeyReservation.<anonymous closure>.<anonymous closure> (package:flutter/src/widgets/framework.dart:2827:20)
#3      _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:617:13)
#4      BuildOwner._debugVerifyGlobalKeyReservation.<anonymous closure> (package:flutter/src/widgets/framework.dart:2822:36)
#5      BuildOwner._debugVerifyGlobalKeyReservation (package:flutter/src/widgets/framework.dart:2891:6)
#6      BuildOwner.finalizeTree.<anonymous closure> (package:flutter/src/widgets/framework.dart:2950:11)
#7      BuildOwner.finalizeTree (package:flutter/src/widgets/framework.dart:3032:8)
